version: '1'

services:
  event-app:
    container_name: event-app
    image: ghcr.io/gunhs/event-app:latest
    volumes:
      - ~/data:/app/data
    environment:
      IMAGE_NAME: event-app
      BOT_NAME: EventBot
      CHAT_ID: ${CHAT_ID:-892237827}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_URL: ${DB_URL}
      PORT: 443
      SSL_ENABLED: true
      TOKEN: ${BOT_TOKEN:5884719976:AAGv5wxiRSS5q4u6sXCpXGbhLN8VkRtCG0E}
    expose:
      - 443
    ports:
      - "443:443"
    restart: always