version: '1'

services:
  event-app:
    container_name: event-app
    image: ghcr.io/event-app:latest
    volumes:
      - ~/data:/app/data
    env_file:
      - ./.env
    environment:
      IMAGE_NAME: event-app
      BOT_NAME: EventBot
      #      CHAT_ID: ${CHAT_ID_DOCKER:-892237827}
      #      DB_PASSWORD: ${DB_PASSWORD_DOCKER}
      #      DB_USER: ${DB_USER_DOCKER}
      #      DB_URL: ${DB_URL_DOCKER}
      PORT: 443
      SSL_ENABLED: true
    #      TOKEN: ${BOT_TOKEN}
    expose:
      - 443
    ports:
      - "443:443"
    restart: always