version: '3'

services:
  event-app:
    container_name: event-app
    image: gunhs/event-app:latest
    volumes:
      - ~/data:/app/data
    env_file:
      - ./.env
    environment:
      BOT_NAME: EventBot
      PORT: 443
      SSL_ENABLED: true
    expose:
      - 443
    ports:
      - "443:443"
    restart: always