version: '1'

services:
  event-app:
    container_name: event-app
    image: ghcr.io/gunhs/event-app:latest
    volumes:
      - ~/data:/app/data
    environment:
      IMAGE_NAME: event-app
      BOT_NAME: EventBot
      CHAT_ID: ${CHAT_ID_PROD:-892237827}
      DB_PASSWORD: ${DB_PASSWORD_PROD}
      DB_USER: ${DB_USER_PROD}
      DB_URL: ${DB_URL_PROD}
      PORT: 443
      SSL_ENABLED: true
      TOKEN: ${BOT_TOKEN}
    expose:
      - 443
    ports:
      - "443:443"
    restart: always