telegram:
  botName: SearchForMessagesBot
  token: 5884719976:AAGv5wxiRSS5q4u6sXCpXGbhLN8VkRtCG0E

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/database;
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect