telegram:
  botName: EventBot
  token: 6082218143:AAF2cX5McrF-w6lIaAuoU0HCOwB8fjflLa0

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./database/events
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true