telegram:
  botName: EventBot
  token: 6082218143:AAF2cX5McrF-w6lIaAuoU0HCOwB8fjflLa0

#telegram:
#  botName: SearchForMessagesBot
#  token: 5884719976:AAGv5wxiRSS5q4u6sXCpXGbhLN8VkRtCG0E

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./database/events
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    ru.sharanov: INFO
  appenders:
    file:
      name: File_Appender
      filename: logs/newlogger.log
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  Loggers:
    Logger:
        -
          name: ru.sharanov.SearchForMessagesBot.Handler
          level: info
          AppenderRef:
            ref: File_Appender
            level: info
